### PR TITLE
chore: Bump dll to 2.5.0

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
### Description

 - Bump dll to 2.5.0

### Compatibility

| Target framework of dll / Runtime | .NET 6   | .NET 7  | .NET 8  |
|---|---|---|---|
| 6  | 88ms  | 82ms  | 70ms  |
|  7 | 90ms  |  85ms | 69ms  |
|  8 | N/A  | N/A  | 70ms  | 

(test benchmark method: `test_benchmark_hurst_longlong `)

### Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or run the performance tests that depict optimal execution times
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by DaveSkender — APPROVED** [review]

**Comment by LeeDongGeon1996** [comment]
@DaveSkender , Could you check CI trigger?

**Comment by DaveSkender** [comment]
> @DaveSkender , Could you check CI trigger?

Yep, not sure what's going on there.  Checking ...

**Comment by LeeDongGeon1996** [comment]
Thanks!! 😁

**Comment by DaveSkender** [comment]
Go ahead and merge and let me know if you want this deployed to PyPI now vs. later.  I've added an issue as a reminder for us to migrate to GitHub Action build and deployments like I've done recently for the C# project.

**Comment by LeeDongGeon1996** [comment]
Thanks. I have some another tasks for next deployment, so I'll let you know later

**Pull request merged**
