### PR TITLE
chore: Bump pythonnet from 2.5.2 to 3.0.0a1

### LINKED ISSUE #13: Conversion issue of Pythonnet for Enum class
## The problem

  - Cannot pass Python Enum as C# Enum.
  - Pythonnet automatically converts C# Enums to `int`.
  - It seems like 'Pythonnet' is still trying to fix this issue. They said this problem will be fixed in version 3.0 and I think we cannot wait for it. The milestone for version 3.0 indicates  41% yet. 

Error message(s):
In Macbook Air(M1), Pythonnet uses Mono runtime for .Net.
Error messages are not quite helpful...

```bash
=================================================================
        Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
        0x10c33cd75 - /Users/<username>/opt/anaconda3/envs/skender/lib/libmonosgen-2.0.1.dylib : mono_dump_native_crash_info
        0x10c2d7b8e - /Users/<username>/opt/anaconda3/envs/skender/lib/libmonosgen-2.0.1.dylib : mono_handle_native_crash
        0x10c33782b - /Users/<username>/opt/anaconda3/envs/skender/lib/libmonosgen-2.0.1.dylib : altstack_handle_and_restore

...skip...
```

## To Reproduce

1. Checkout to the branch, `feat/support-candlepart-sma` in my forked repo.
2. Run `pytest -svr A`

## Related Indicators
 - Williams
 - EMA
 - Stoch  Oscillator
 - Beta
 - ZigZag
 - Chandelier
 - MaEnvelopes
 - Pivot Points
 - Pivots

### LINKED ISSUE #58: `IEnumerable` won't be auto-converted in pythonnet 3.0.0
## The problem

Pythonnet will not convert `IEnumerable` of C# to `list` of Python anymore from the version 3.0.0.
Our `_verify_data()` method checks the data is subclass of `list` or not and so it'll never be passed.
That means testcases will be failed if we use pythonnet 3.0.0.

https://github.com/DaveSkender/Stock.Indicators.Python/blob/36c45c5d118d360e4a40650996cee1690fe329f0/stock_indicators/indicators/common/results.py#L57

##  Related Issue
 - https://github.com/pythonnet/pythonnet/issues/1622

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
### Description

 - Bump pythonnet from 2.5.2 to 3.0.0a1 .

Fixes #13 , Fixes #58 

### Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or run the performance tests that depict optimal execution times
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by LeeDongGeon1996** [comment]
Just wondering. There are three security checks, CodeQL, LGTM and snyk. Do they have different purpose of security check? or just for more security?

**Comment by DaveSkender** [comment]
> Just wondering. There are three security checks, CodeQL, LGTM and snyk. Do they have different purpose of security check? or just for more security?

I'm undecided on which one I like more, really.  They all operate slightly differently and check for different rules.  LGTM is also doing some general code analysis, not just security checks.  CodeQL was the original one as it was super easy to incorporate through normal GitHub features.

**Review by DaveSkender — APPROVED** [review]

**Comment by LeeDongGeon1996** [comment]
@DaveSkender Okay :)

**Comment by LeeDongGeon1996** [comment]
@DaveSkender Do you mind if I add code quality badge from LGTM to README.md? ;)

**Pull request merged**
