### PR TITLE
docs: Update docs for v0.8.1

### LINKED ISSUE #244: error: "PeriodSize" is not defined
I wrote the pivot points code with python in vscode but vscode had some error in indicator parameter defining.
p1

What's my mistake?

_Originally posted by @Gadirino in https://github.com/DaveSkender/Stock.Indicators/discussions/274#discussioncomment-3364313_

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
### Description

 - Update docs for import path.
 - Updates for v0.8.1

Fixes #244 

### Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or run the performance tests that depict optimal execution times
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by LeeDongGeon1996** [comment]
Because `from stock_indicators.indicators.common.enums import PivotPointType` is shortened to `from stock_indicators import PivotPointType` in the docs, 4f9e2155b7faaaeeedd615f5dc01af08a743bbec have to be cherrypicked from the `tag 0.8.0`, and released as 0.8.1 with patch-version up.

**Review by DaveSkender — APPROVED** [review]

**Comment by DaveSkender** [comment]
> I think I need a new branch from `tag 0.8.0`. Could you make it as a protected branch with named `0.8`?

I’m not sure I follow this logic.  Is this a `rebase` issue, or something we can just fix in a second commit (before releasing)?

**Comment by LeeDongGeon1996** [comment]
I'd like to include only  4f9e215 in v0.8.1 (because it's related UX). But we are merging every PR to `main` till now. So there's no way to exclude some un-released commits before  4f9e215 . That's why I need a new branch to make a backport.

**Comment by DaveSkender** [comment]
I've created a branch `v0.8` from that tag.

**Pull request merged**
