### PR TITLE
chore: Bump DLL from 1.23.1 to 2.4.0

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
### Description

 - Bump DLL from 1.23.1 to 2.3.0

### Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or run the performance tests that depict optimal execution times
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by LeeDongGeon1996** [comment]
@DaveSkender I think that there's no way to calc SMA with other price value (not `close` value) by using v2.3.0(C#) api, because we currently don't have chaining or `BasicData` feature.

**Comment by DaveSkender** [comment]
You're really getting into the chaining features going that route.  It might be simpler to just stick with the basic API, then come back to adding the chaining parts.

https://github.com/DaveSkender/Stock.Indicators/blob/c861415538c93d04626a3c8df618cfadc153deeb/src/s-z/Sma/Sma.Api.cs#L9-L14

**Comment by LeeDongGeon1996** [comment]
Yeah, the problem comes from that. The basic API of SMA can calculate from only `close` values. Is it intentional?

**Comment by DaveSkender** [comment]
> Yeah, the problem comes from that. The basic API of SMA can calculate from only `close` values. Is it intentional?
> I'd like to provide options so that users can select which OHLCV used for calculating.

Ah, I forgot we had that parameter before, on both SMA and EMA.  I removed it because with the chainable `Use()` it wouldn’t be needed.  Can you think of a simple way to keep the old wrapper API with the new DLL for these two?

**Comment by LeeDongGeon1996** [comment]
It work well with any of the both. I'm just curious. why it does not work with `GetBaseQuote()`? It shows the error like the below.
```bash
E       System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
E          at Skender.Stock.Indicators.Indicator.ToResultTuple(IEnumerable`1 basicData)
E          at Skender.Stock.Indicators.Indicator.GetSma(IEnumerable`1 results, Int32 lookbackPeriods)
```

**Comment by LeeDongGeon1996** [comment]
@DaveSkender Just for double-check, are test values the only changes in PRS and Renko?

**Comment by DaveSkender** [comment]
Were you able to check that the breaking changes listed in https://github.com/DaveSkender/Stock.Indicators/pull/802 are considered here?  Most easily missed is the swapping of parameter locations for Beta and PRS.

**Comment by LeeDongGeon1996** [comment]
Thank you for letting me know.
Breaking changes on v2 dll

- [ ] numerous result values and some parameters changed from decimal to double
- [ ] result class is now sealed and cannot be used as a derived class (required for reusable chaining), though you can just replicate the class properties
- [ ] IMPORTANT!: Beta and Price Relative Strength (PRS) have swapped positions of Eval and Base (Market) quote parameters positions, for consistency. Since these have the same data type profile, it does not naturally produce a warning! A warning is forced on v2.0.0 only as a precaution but will be removed in the next released version.
- [ ] GetSmaExtended() was renamed to GetSmaAnalysis(). We'll expand on and improve extended analysis broadly in future versions. See https://github.com/DaveSkender/Stock.Indicators/discussions/320 on how this may change in the future.
- [ ] ~results now return NaN instead of null in random div/0 scenarios; though, we intend to revert this change to reduce user friction, see https://github.com/DaveSkender/Stock.Indicators/issues/839~ (Related with chaining)

**Review by DaveSkender — APPROVED** [review]
See related to do items above.  Pre-approving.

**Comment by LeeDongGeon1996** [comment]
I think it's better to add related documentation right before releasing in another PR :)

**Comment by DaveSkender** [comment]
> I think it's better to add related documentation right before releasing it in another PR :)

Sure

**Pull request merged**
