### PR TITLE
tests: Add tests for helper methods

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
## Description

 - Add test for helper methods
   - `find()`
   - `remove_warmup_periods(qty)`

## Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or run the performance tests that depict optimal execution times
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by DaveSkender — APPROVED** [review]
Looks good.  On a side note, one of the changes I'm experimenting with right now in the core DLL is to change many of the `decimal` representations (mostly results classes) to `double` floating-point precision; which should map better to Py `float`.  Might help speed things up in the wrapper.

**Comment by LeeDongGeon1996** [comment]
@DaveSkender That sounds great. And more, in the future, I have a plan to add `dtype` to support user to get output with desired type.

For example:
 - https://numpy.org/doc/stable/reference/generated/numpy.array.html

**Comment by DaveSkender** [comment]
I’ve been doing a broader [analysis on precision vs performance](https://github.com/DaveSkender/Stock.Indicators/discussions/649) and I think we’ll be able to partially make the switch.  I need to do a bit more testing to be sure.

**Comment by LeeDongGeon1996** [comment]
Now I get it, what the problem is. Great analysis note. I don't know much of financial things, but let me know if there's something I can help.

**Pull request merged**
