### PR TITLE
ci: Add Codacy code coverage

### PR DESCRIPTION
**Pull request by DaveSkender**
This only publishes the code coverage report to Codacy, for completeness of that record.

### CODE REVIEW

**Comment by DaveSkender** [comment]
@LeeDongGeon1996 you should be able to login to Codacy, I have you set as a user however, I’m not quite sure you have all the visibility that I do.

**Comment by LeeDongGeon1996** [comment]
@DaveSkender it's working! the problem was format of reporting file. It requires cobertura.xml format.

**Comment by DaveSkender** [comment]
Hehe, I actually initiated the PR, so you'll have to approve it.  LGTM.

**Review by LeeDongGeon1996 — APPROVED** [review]

**Comment by LeeDongGeon1996** [comment]
@DaveSkender I cannot find our repository on my Codacy dashboard. Can you check about it?

**Pull request merged**
