### PR TITLE
feat: Add Heikin-Ashi

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
### Description

 - Add Heikin-Ashi.

### Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [ ] I have added or run the performance tests that depict optimal execution times
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by DaveSkender — APPROVED** [review]

**Comment by DaveSkender** [comment]
These errors are from the new v1.20.0 DLL.  I'd suggest adding it to the repo for development purposes, in a separate PR.  A few input, and many output parameters were changed from `decimal` to `double`.  The new DLL is 2x faster than before.

**Comment by LeeDongGeon1996** [comment]
@DaveSkender Thank you for letting me know. Then, we need to add previous version of DLL and remove some steps like "fetching from artifacts" in `build.main.yml`?

**Comment by DaveSkender** [comment]
> remove some steps like "fetching from artifacts" in `build.main.yml`?

No need to modify the build, it’s doing what it is supposed to do to use the last released DLL.  Just update the one in the `stock_indicators/_cslib/lib` Folder and fix the data types here so they are compatible.

**Comment by LeeDongGeon1996** [comment]
@DaveSkender Oh, I got what you mean. I think it's nice time to add `dtype` feature to be flexible for the data type.

**Pull request merged**
