### PR TITLE
docs: general updates for v0.2.0

### PR DESCRIPTION
**Pull request by DaveSkender**
### Description

General documentation updates

### Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or run the performance tests that depict optimal execution times
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by DaveSkender** [comment]
Updraft when ready.  Looks like you still have a bunch of broken URLs

**Comment by LeeDongGeon1996** [comment]
@DaveSkender It's ready to be reviewed! Please have a check and let me know when you finish.

**Comment by LeeDongGeon1996** [comment]
We've lost the purpose of this branch. It should have changes only for docs so that it can be merged after releasing, but it has some changes to be merged in the release. There will be time interval btw docs and release. haha,,

**Comment by DaveSkender** [comment]
Looks good generally.  I can’t approve since I created it, so you’ll have do it.

**Review by LeeDongGeon1996 — APPROVED** [review]
Yep, Approved.

**Pull request merged**
