### PR TITLE
chore: Add auto-versioning

### LINKED ISSUE #38: Auto-increment versions in build
One thing I'm going to want to do in the build before we do a public publish is to auto-update the version number in the build process.  The `GitVersion` build task produces an environment variable `$(GitVersion.MajorMinorPatch)` that I think we can use to text replace  `version="0.0.0"` in `setup.py`.  I'm not sure of the best way to do that with Python commands; however, the worst case is we just do a straight text replacement in the `setup.py` file in the build process.  I'd like the build system to manage the version numbers and not rely on manually updating `setup.py`.

Ref: https://gitversion.net/docs/reference/variables
Observed in #28

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
## Description

 - Auto-versioning using gitversion.

Fixes #38 

## Checklist

- [ ] My code follows the existing style, code structure, and naming taxonomy
- [ ] I have performed a self-review of my own code and included any verifying manual calculations
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings and running code analysis does not produce any issues
- [ ] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage
- [ ] I have added or run the performance tests that depict optimal execution times
- [ ] New and existing unit tests pass locally and in the build (below) with my changes

## Acknowledgements

- [ ] I have read and understand [the Apache 2.0 license](https://opensource.org/licenses/Apache-2.0)
- [ ] I agree to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

### CODE REVIEW

**Comment by LeeDongGeon1996** [comment]
I've reset forked repository, it doesn't work.
How about resetting github-token or credentials(like tokens or key-pairs..) used for Azure and github-actions?

**Comment by DaveSkender** [comment]
Just unhooked and rehooked the Azure Pipelines integration; that didn't seem to help.

**Comment by DaveSkender** [comment]
Ok, I've added some upgrades that seem to work in fetching the DLL.  There may be some other items for you to look at in the test setup.

**Comment by LeeDongGeon1996** [comment]
THANKS! seems like the previous one is deprecated as per its documentation.

It keeps failing on Python 3.9. Actually pythonnet doesn't support 3.9.
 - https://github.com/pythonnet/pythonnet/issues/1262
 - [Similar Case] https://github.com/DHI/mikeio1d/pull/21

I don't know why it did work before..
Anyway, I'll change the versions we test on.

**Comment by LeeDongGeon1996** [comment]
@DaveSkender Do you think we need to automate publishing artifacts to internal package manager? In C# implementation, seems like it's done manually.

**Comment by DaveSkender** [comment]
> @DaveSkender Do you think we need to automate publishing artifacts to internal package manager? In C# implementation, seems like it's done manually.

I used to have it set up to auto-publish to Internal after `main` branch commits only; however, I've found that I only really use it when I need to test the package, which is about 10% of the `main` commits these days (most are documentation related).

It seems like a lot of "junk" to keep around for interim feature commits, though Azure DevOps does prune them for us after a while.  

Another issue is, when it's fully automated, handling the unique version constraints that all package managers have; they only allow a single version to exist once and you cannot replace it once it's loaded.  So, for the PR-build example, as long as the suffix is incremented with new changes, it can be done.

I think CD automation might work better for `main` branch commits only IMO.

**Comment by LeeDongGeon1996** [comment]
Yeah, it looks like that gitversion can manage suffix will not be duplicated but I also think that we don't need to keep every bulid(including PRs) in Internal package manager. Let's apply on `main` branch only.

**Comment by LeeDongGeon1996** [comment]
I'm trying to upload PR build to Internal, but I think I don't have permission to upload to Internal. Can you check that for me?

**Comment by DaveSkender** [comment]
> @DaveSkender I'm trying to upload PR build to Internal for testing, but I think I don't have permission to upload to Internal. Can you check that for me?

We've typically separated build vs deploy, so I'd not recommend trying to push (deploy) here in the build.  I've already setup the rig to do that deployment.  See [release pipelines](https://dev.azure.com/skender/Stock.Indicators/_release).

I'll take a look at permissions to make sure you can deploy to Internal in those release pipelines ... they're already setup, so you don't actually need to do anything extra to implement.

**Comment by LeeDongGeon1996** [comment]
> you don't actually need to do anything extra to implement.

That's great. Then, you mean release pipeline, deploying to Internal, doesn't need any yml file to config?

**Comment by DaveSkender** [comment]
> > you don't actually need to do anything extra to implement.
> 
> That's great. Then, you mean release pipeline, deploying to Internal, doesn't need any yml file to config?

yes, that’s correct.  It’s currently on a manual trigger, but can be set to automatically deploy on successful build completion.

**Comment by DaveSkender** [comment]
@LeeDongGeon1996 I think I updated your permits correctly on Azure DevOps.  You should be able to login with your GitHub account and trigger Releases to Internal package managers now + edit the definition.

**Comment by LeeDongGeon1996** [comment]
> @LeeDongGeon1996 I think I updated your permits correctly on Azure DevOps. You should be able to login with your GitHub account and trigger Releases to Internal package managers now + edit the definition.

It works. Thanks!

**Comment by LeeDongGeon1996** [comment]
@DaveSkender  I've set branch filter to main on CD trigger. Is there anything else we should do in this task?

**Comment by DaveSkender** [comment]
I just tried to deploy this PR package, not sure if this will happen with `main` version, but it doesn’t like the extended version number.  Error says the version should conform to PEP 440.  If it works for `main`, can probably be okay.

**Review by DaveSkender — APPROVED** [review]
I’d recommend:

- explore another git version variable specifically for PRs, can live with it as is, but we’d not be able to do prereleases from PR builds
- Merge the PR and see if it works!

**Comment by LeeDongGeon1996** [comment]
It will be related with [this comment](https://github.com/DaveSkender/Stock.Indicators.Python/issues/38#issuecomment-955675786) in #38. As I searched, It won't be the problem in `main` branch.

**Pull request merged**
