### PR TITLE
docs: general updates for v0.3.0

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
### Description

 - Update docs.

### Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or run the performance tests that depict optimal execution times
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by LeeDongGeon1996** [comment]
@DaveSkender  I'm thinking of adding some more infos in README.md because it's a landing page that can give first impression to visitors. It would be more attractive if they can see how to install and simple usage on README even though it is duplicated with GUIDE.me. I'm asking you because you removed them before intentionally. How do you think?

**Comment by DaveSkender** [comment]
> @DaveSkender I'm thinking of adding some more infos in README.md because it's a landing page that can give first impression to visitors. It would be more attractive if they can see how to install and simple usage on README even though it is duplicated with GUIDE.md. I'm asking you because you removed them before intentionally. How do you think?

Yah, I have a bit of that on the .NET one, mostly to show how simple the interface is.  Though, I do treat the webpage Home Screen differently than the repo README.Md, mostly because that repo readme gets thrown over to the package site and I want users to go over to the website for a better experience.

**Comment by LeeDongGeon1996** [comment]
I've changed my mind not to change readme. but what I'm thinking is that the better way to get users go to 'Getting started' at a glance. For now, I don't have any idea, so let's just keep as it is.

**Comment by DaveSkender** [comment]
So, I did something that's going to blowup your build.  I basically removed all the `BadQuotesException` cases in the library, so you'd not need to test for that anymore (and can remove those tests).

**Review by DaveSkender — APPROVED** [review]

**Pull request merged**
