### PR TITLE
feat: Add McGinley Dynamic

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
### Description

 - Add McGinley Dynamic

### Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or run the performance tests that depict optimal execution times
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by LeeDongGeon1996** [comment]
@DaveSkender maybe I don't have permission to publish test-coverage?

**Comment by DaveSkender** [comment]
> @DaveSkender maybe I don't have permission to publish test-coverage?

The new test reporter I was experimenting with is a bit flaky; I've just disabled it.

**Review by DaveSkender — APPROVED** [review]
LGTM.  Were you planning to add docs page separately?

**Comment by LeeDongGeon1996** [comment]
> Were you planning to add docs page separately?

Yeah, since we merge directly into the main branch, I think it is better to add docs as soon as possible before we deploy new features.

**Pull request merged**
