### PR TITLE
feat: Add ROC

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
### Description

 - Add ROC

### Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [ ] I have added or run the performance tests that depict optimal execution times
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by DaveSkender — APPROVED** [review]
What's your opinion on adding related docs to these?
I typically do it all together, but the downside is that they publish to the site before the package, which can cause some users confusion.

**Comment by LeeDongGeon1996** [comment]
My plan is to make separate branch for docs of indicators which is not deployed yet. By doing that, we can keep updating docs without confusing. When we release new indicators, what we need to do is just merging them. How do you think?

**Comment by DaveSkender** [comment]
> My plan is to make separate branch for docs for indicators which are not deployed yet. By doing that, we can keep updating docs without confusing. When we release new indicators, what we need to do is just merging them. How do you think?

Makes sense.  That solved my bad timing issue -- just merge the docs once the next release is ready.  It might be helpful to get that branch started and open a Draft PR so they can be linked, reviewed, and tracked together, even if in separate branches.

**Comment by LeeDongGeon1996** [comment]
Yep, let's go with it

**Pull request merged**
