### PR TITLE
feat: Add `dtype` for results

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
BY SUBMITTING A PULL REQUEST AND CHANGES TO THIS REPOSITORY YOU ARE ACKNOWLEDGING AND AGREE TO THE TERMS IN BOTH THE [DEVELOPER CERTIFICATE OF ORIGIN](https://developercertificate.org) AND THE [APACHE 2.0 LICENSE](https://opensource.org/licenses/Apache-2.0).

PLEASE REMOVE EXPLANATORY TEXT AND UNNEEDED SECTIONS BEFORE CREATING PULL REQUEST.  CREATE A DRAFT PULL REQUEST IF YOU INTEND TO ADD MORE COMMITS.  REMOVE DRAFT STATUS AND REQUEST REVIEW FROM `DaveSkender` and `LeeDongGeon1996` WHEN YOU ARE READY TO COMMIT CHANGES.

### Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation, context, and sources of information or recipes.

 - refactor: change decimal to float

### Checklist

- [ ] My code follows the existing style, code structure, and naming taxonomy
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have performed a self-review of my own code and included any verifying manual calculations
- [ ] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [ ] My changes generate no new warnings and running code analysis does not produce any issues
- [ ] I have added or run the performance tests that depict optimal execution times
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by LeeDongGeon1996** [comment]
@DaveSkender It suddenly came to me that we might not need dtype feature for this. I originally thought that dtype might be needed when users want to get a result with a specific datatype. Of course, if the datatype, having more precise than its original result datatype from C# core, is given, it can guarantee only to its original precision. But when there are users who want precision only to one decimal point, they can pass `float16` of Numpy as a dtype(Or just can use `round()`). And someone may want to set specific types for the results.
But, with that said, I'm still not sure that these are worth to be provided as options. How do you think?

**Comment by DaveSkender** [comment]
> @DaveSkender It suddenly came to me that we might not need dtype feature for this. I originally thought that dtype might be needed when users want to get a result with a specific datatype. Of course, if the datatype, which is more precise than its original result datatype from C# core, is given, it can guarantee only to its original precision. But when there are users who want precision only to one decimal point, they can pass `float16` of Numpy as a dtype(Or just can use `round()`). And someone may want to set specific types for the results. But, with that said, I'm still not sure that these are worth to be provided as options. How do you think?

One thing I'm finding is that _most_ outputs to not really need that much precision.  I'd suggest to implement the approach that's easiest for the user to handle.  As long as the unit tests pass, the precision is likely sufficient for 99.9% of all use cases.

**Comment by LeeDongGeon1996** [comment]
Yeah, the point is whether users can get the results with their desired type they would like to handle. Might be helpful or might not. Let's just give an option and have a look later if users really need it or not.

**Comment by DaveSkender** [comment]
> Yeah, the point is whether users can get the results with their desired type they would like to handle. Might be helpful or might not. Let's just give an option and have a look later if users really need it or not.

Just keep in mind, extra features are not always better if it adds confusion, complexity, or reduces performance.

**Comment by LeeDongGeon1996** [comment]
> Just keep in mind, extra features are not always better if it adds confusion, complexity, or reduces performance.

Sure.

**Comment by LeeDongGeon1996** [comment]
@DaveSkender I finally decided not to add dtype feature. This functionality can be achieved in many other ways by users manually. I also think that users may not use its results as is and they may input or convert the results in their desired use.

**Comment by DaveSkender** [comment]
> @DaveSkender I finally decided not to add dtype feature. This functionality can be achieved in many other ways by users manually. I also think that users may not use its results as is and they may input or convert the results in their desired use.

I had come to this conclusion as well in the base library.  Be unopinionated and let the user decide how to handle output + xtra features usually come at a performance cost.

**Comment by LeeDongGeon1996** [comment]
You're right, it is better to let them choose how to handle.

**Pull request closed without merging**
