### PR TITLE
feat: Support CandlePart for WMA

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
### Description

 - Support CandlePart for WMA.

### Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or run the performance tests that depict optimal execution times
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by LeeDongGeon1996** [comment]
It looks like it fetches unreleased version of dll when replace dll to the latest.

**Comment by DaveSkender** [comment]
This DLL auto-fetcher should only take the latest package from `main` builds with the `release` tag.  It looks like it's not considering the `release` tag and taking the latest `main` build package instead.

**Review by DaveSkender — APPROVED** [review]
Other than the build issue, this looks ok.

**Comment by LeeDongGeon1996** [comment]
> This DLL auto-fetcher should only take the latest package from `main` builds with the `released` tag. It looks like it's not considering the `released` tag and taking the latest `main` build package instead.

You mean it is temporary issue on Azure?

**Comment by LeeDongGeon1996** [comment]
Umm.. I think that it's a bad idea to use unreleased dll from manual build to avoid this issue. Could you force-merge it, if possible?

**Comment by DaveSkender** [comment]
> Umm.. I think that it's a bad idea to use unreleased dll from manual build to avoid this issue. Could you force-merge it, if possible?

Yes, I agree, it's bad.  It's not supposed to do that and I'm not sure why it is doing it suddenly.  I _think_ it was working properly before.  I can't troubleshoot at the moment, but may be able to look at it later.

It's probably okay to override the merge, as long as the code is good and we don't release this version before we get a good build.  Is that what you want to do here?

**Comment by LeeDongGeon1996** [comment]
> It's probably okay to override the merge, as long as the code is good and we don't release this version before we get a good build. Is that what you want to do here?

Yeah, I think we can ignore CI test for now and just merge. This failure is false negative.

**Pull request merged**
