### PR TITLE
docs: Add blurb for trouble with converting to quotes

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
### Description

 - Add blurb for trouble with converting to quotes

### Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or run the performance tests that depict optimal execution times
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by LeeDongGeon1996** [comment]
I've just add short blurb as we discussed and this is for general cases, not only for `locale` issue.

**Review by DaveSkender — APPROVED** [review]

**Comment by DaveSkender** [comment]
I'm done tweaking, go ahead and merge if you're ready.

**Comment by LeeDongGeon1996** [comment]
@DaveSkender  do we have code coverage badge from Codacy now? I can't find with my permission.

**Comment by DaveSkender** [comment]
> @DaveSkender do we have code coverage badge from Codacy now? I can't find with my permission.

I've removed them from the _permanent_ `README.md` aspects that get published with packages given how much trouble they've been.  You probably can't see this [settings page](https://app.codacy.com/gh/DaveSkender/Stock.Indicators.Python/settings) with the badge info.

[Codacy Badge](https://app.codacy.com/gh/DaveSkender/Stock.Indicators.Python/dashboard)

**Comment by LeeDongGeon1996** [comment]
> given how much trouble they've been. 

You mean showing this badge has had trouble frequently?

**Comment by DaveSkender** [comment]
> You mean showing this badge has had trouble frequently?

1. It's just been hard to get them to work with Codacy
2. Legacy package manager pages that are _permanent_ have old Azure badges that are now broken when I turn off those old builds; pages like on [nuget.org](https://www.nuget.org/packages/Skender.Stock.Indicators/2.4.12#readme-body-tab) and [pypi.org](https://pypi.org/project/stock-indicators/1.1.0/)

**Comment by LeeDongGeon1996** [comment]
@DaveSkender I added in the same page. 
Could you [set ignoring some files in Codacy](https://docs.codacy.com/repositories-configure/ignoring-files/)?

**Comment by DaveSkender** [comment]
> @DaveSkender I added in the same page. Could you [set ignoring some files like docs or tests in Codacy](https://docs.codacy.com/repositories-configure/ignoring-files/)?

Updated:
image

**Pull request merged**
