### PR TITLE
Enable timezone-aware datetime instances for Quotes by utilizing dateutil package.

### PR DESCRIPTION
**Pull request by claytonEtillman**
### Description

An error is produced in the current version when trying to export `result.date` if the input `Quote.date` was timezone-aware. The problem is that, according to the Python docs, prior to Python 3.11 the function `datetime.datetime.fromisoformat` "does not support parsing arbitrary ISO 8601 strings - it is only intended as the inverse operation of [datetime.isoformat()](https://docs.python.org/3.10/library/datetime.html#datetime.datetime.isoformat). A more full-featured ISO 8601 parser, dateutil.parser.isoparse is available in the third-party package [dateutil](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.isoparse)." While this is fixed in Python 3.11, I put in the fix in this pull request for backwards-compatibility. Most of the libraries I use have not upgraded to Python 3.11 yet.

Below is a screenshot of the failing tests I added before putting in the fix. These originate from calling `result.date` after using an 'aware' `datetime.datetime` instance as input.

image

**CAUTION** I also ran benchmarks on the `aware` instances with a few indicators, and _there is a significant decrease in performance_ when using 'aware' `datetime`s. See screenshot below.

image

Fixes #-
I did not put an issue in as I had already fixed this on my local installation. I figured I might as well share this so that others can use it if they are on a Python lower than 3.11.

### Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or run the performance tests that depict optimal execution times
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by claytonEtillman** [comment]
Haha, it looks like the server is on UTC time and my machine is on EDT so we have a mismatch on output although the times are the same. I should be doing a timezone-aware comparison! How ironic. I'll make the necessary changes sometime this week.

**Comment by DaveSkender** [comment]
If it helps, dates passed through this library are merely data labels, so converting to a time zone aware format isn’t helpful for anything it does; however, I so see how someone sending in with TZ aware formats would want it to come back in that same format.

**Comment by LeeDongGeon1996** [comment]
I'll have a look tonight.

**Comment by LeeDongGeon1996** [comment]
Hi, first of all, thanks for your contribution :)

@DaveSkender  Do you mean that `datetime` data in financial markets is usually provided in not timezone-aware form?
I think it's worth it in terms of backward-compatibility. If there's someone having timezone-aware data, they will not care about whatever their date format is and struggle with the error from timezone-aware data.

**Comment by DaveSkender** [comment]
> Hi, first of all, thanks for your contribution :)
> 
> @DaveSkender Do you mean that `datetime` data in financial markets is usually provided in not timezone-aware form? I think it's worth it in terms of backward-compatibility. If there's someone having timezone-aware data, they will not care about whatever their date format is and struggle with the error from timezone-aware data.

Yes, it'll usually comes from sources without timezone offset information at intrinsic regional market time or UTC time, without any offset information.  For example, most U.S- based market data is in Eastern Time Zone, but someone could encode it with [timezone offest information](https://wikipedia.org/wiki/Time_zone#Notation) as Z-5 if they wanted to.

This is really a matter of how much cost (e.g., to performance and extra features) do we want to bear to accommodate its use in quotes people provide.  I don't think I'll change the .NET library from DATETIME to DATETIMEOFFSET either, it's way too expensive with little value.

**Comment by claytonEtillman** [comment]
Hi @DaveSkender & @LeeDongGeon1996, thank you for the great library! I appreciate the feedback. Please see below how I encountered this error.
```
stoch_rsi_results = si.get_stoch_rsi(quotes_list, R, S, G, M).remove_warmup_periods()
rsi_df = pd.DataFrame([ (r.date, r.stoch_rsi, r.signal) for r in stoch_rsi_results ], columns=['TimeStamp','stoch_rsi','rsi_signal'])
```
The TradeStation API returns data in UTC time with a 'Z' marker to indicate the timezone: [TradeStation API specification](https://api.tradestation.com/docs/specification#tag/MarketData/operation/GetBars). I convert this datetime to Eastern for New York exchanges before calling the stock-indicators functions. If someone is using this library for other exchanges, they may use that exchange's local timezone. I then load the results to a pandas DataFrame to merge back in with my other data based on `datetime`, which I've named `TimeStamp`. I convert both DataFrames that I'm merging to Eastern time for New York exchanges. As long as they are both timezone aware, this works. It's okay if it changes timezones as long as it knows which timezone it has changed to.

The errors in the GitHub build are due to trying to compare them as strings in the tests I added. I'll put a fix in for those shortly.

**Comment by claytonEtillman** [comment]
> I don't think I'll change the .NET library from `DateTime` to [DateTimeOffset](https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset) either, it's way too expensive and can get really goofy, with little value. It's possible that I'm overthinking this as there might be some simple tweak here that just works.

It doesn't seem to need a tweak in the C# code. It comes back timezone aware from what I can tell. It just has one too many zeros in the fraction of seconds. The use of the Python dateutils `isoparse` function compensates for that adequately.

**Comment by claytonEtillman** [comment]
Concerning the computational cost, it doesn't seem to increase unless someone uses a timezone aware datetime. The dateutils function seems comparable to the datetime function in computation speed. Also, I give 2000 rows for the tz aware benchmark test, which is four times the data in the default dataset. Maybe this is the cause of the increased computation time.

**Comment by claytonEtillman** [comment]
I fixed the tests: just needed to compare them as dates.

I didn't push the added benchmarks I ran because the docs say not to update the Excel file, but I have those stashed if you want me to. Just let me know.

**Comment by claytonEtillman** [comment]
I have yet one more set of fixes to make. While I normally put standard library imports before third-party with clearer separation, I tried to follow the format of the library. I like 'import' statements together and 'from' statements together. I'll fix that quickly.

**Comment by LeeDongGeon1996** [comment]
Sorry for late reply, I'll have a look tonight.

**Pull request closed without merging**
