### PR TITLE
Add auto-versioning

### PR DESCRIPTION
**Pull request by LeeDongGeon1996**
PLEASE REMOVE EXPLANATORY TEXT AND UNNEEDED SECTIONS BEFORE CREATING PULL REQUEST.  CREATE A DRAFT PULL REQUEST IF YOU INTEND TO ADD MORE COMMITS.  REMOVE DRAFT STATUS AND REQUEST REVIEW FROM ANY OF OUR CORE CONTRIBUTORS WHEN YOU ARE READY TO COMMIT CHANGES.

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation, context, and sources of information or recipes.

Fixes #

## Checklist

- [ ] My code follows the existing style, code structure, and naming taxonomy
- [ ] I have performed a self-review of my own code and included any verifying manual calculations
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings and running code analysis does not produce any issues
- [ ] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage
- [ ] I have added or run the performance tests that depict optimal execution times
- [ ] New and existing unit tests pass locally and in the build (below) with my changes

## Acknowledgements

- [ ] I have read and understand [the Apache 2.0 license](https://opensource.org/licenses/Apache-2.0)
- [ ] I agree to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

### CODE REVIEW

**Comment by LeeDongGeon1996** [comment]
@DaveSkender Can you the error message on Pipelines? I've changed nothing, but it's failed to build.

**Comment by DaveSkender** [comment]
> @DaveSkender Can you the error message on Pipelines? I've changed nothing, but it's failed to build.

Seems to not like this task step:

```yml
      - task: DownloadPipelineArtifact@2
        displayName: "Fetch NuGet DLL"
        inputs:
          source: specific
          project: 5123ca47-74f2-4d67-a5d4-c4d90b8d670a
          pipeline: 21
          runVersion: latestFromBranch
          runBranch: refs/heads/main
          artifact: packages
          patterns: "packages/*.nupkg"
```
with error:

```bash
Download from the specified build: #3493
Download artifact to: /home/vsts/work/1
##[error]The container 3177214 could not be found.
```

I've double-checked the `project` GUID and it looks fine; and it looks like it's identifying the correct build 3493 to get the stuff + the packages look okay in that build.  Not sure what's happening.  Could be an issue in Azure DevOps.

**Comment by DaveSkender** [comment]
May need to post an Issue here, not sure yet.  Re-run still produces error.
https://github.com/microsoft/azure-pipelines-tasks

**Comment by LeeDongGeon1996** [comment]
I'm also suspicious that we might lose access permission while converting to public from private because github-action-

**Comment by DaveSkender** [comment]
> It's also suspicious that we might have lost access permission while converting to public from private because [github-actions-automate-projects](https://github.com/DaveSkender/Stock.Indicators.Python/runs/4178182905?check_suite_focus=true) is showing 403 error. It might have same reason with Azure DevOps.

That’s a good point, your Fork may need to be reset.

**Comment by LeeDongGeon1996** [comment]
Continue in #49

**Pull request closed without merging**
